### ISSUE TITLE
Contributing / Collaborating 👋

### ISSUE THREAD

**Issue by Offroaders123** [Kas-tle/java2bedrock#1]
Hello!

I was looking to find a better way to contact you, but this is the best I found.

I saw you starred my NBTify project, so I came to see what you work on as well. I've been working to set up a world converter in TypeScript for a while, and a while back (before I got into programming) I wanted to make a resource pack converter as well.

I was wondering if you'd like to talk more on Discord or something like that, it seems like we might have common goals for things we're trying to build, any insights to your thoughts on getting things setup would be awesome! Working with NBT has been a fun thing I've been trying to make easy lately too, so I'd be happy to help with that, NBTify might be able to help make life easier for what you might be building.

Brandon

edit: My Discord is the same as my name here, `offroaders123`.

**Comment by Kas-tle** [comment]
Sure happy to talk. I sent a friend request on Discord.
